#!/bin/bash

# aterm.jar download link
ATERM_URL=https://mediaflux.vicnode.org.au/mflux/aterm.jar

# download function
download() {
    if [[ -z $(which curl) && -z $(which wget) ]]; then
        echo "Error: cannot download aterm.jar. No curl or wget found." 1>&2
        return 1
    fi
    local out="$1"
    local url="$2"
    if [[ ! -z $(which curl) ]]; then
        curl -f --create-dirs -k -o "${out}" "${url}"
    else
        wget --no-check-certificate -O "${out}" "${url}"
    fi
    return $?
}

# download aterm function
download_aterm() {
    [[ -z $MFLUX_ATERM || ! -f $MFLUX_ATERM ]] && MFLUX_ATERM=/opt/mediaflux/bin/aterm.jar
    [[ -z $MFLUX_ATERM || ! -f $MFLUX_ATERM ]] && MFLUX_ATERM=./aterm.jar
    [[ -z $MFLUX_ATERM || ! -f $MFLUX_ATERM ]] && MFLUX_ATERM=$(dirname $0)/aterm.jar
    if [[ -z $MFLUX_ATERM || ! -f $MFLUX_ATERM ]]; then
        download "${MFLUX_ATERM}" "${ATERM_URL}"
        if [[ $? -ne 0 ]]; then
            echo "Error: failed to download aterm.jar"
            return 1
        else
            return 0
        fi
    else
        return 0
    fi    
}

# detect java
[[ -z $(which java) ]] && echo "Error: cannot find java." 1>&2 && exit 1

# detect aterm.jar
download_aterm || exit 1

# detect mflux.cfg
MFLUX_CFG=$HOME/.Arcitecta/mflux.cfg
[[ -z $MFLUX_CFG || ! -f $MFLUX_CFG ]] && MFLUX_CFG=$./mflux.cfg
[[ -z $MFLUX_CFG || ! -f $MFLUX_CFG ]] && MFLUX_CFG=$(dirname $0)/mflux.cfg
[[ -z $MFLUX_CFG || ! -f $MFLUX_CFG ]] && echo "Error: cannot find mflux.cfg." 1>&2 && exit 1

# show usage if no arguments specified
if [[ $# -eq 0 ]]; then
    echo "Error: missing arguments." 1>&2
    java -jar -Dmf.cfg=$MFLUX_CFG $MFLUX_ATERM nogui help import | sed 's/import:/aterm-import:/' | sed 's/import \[/aterm-import \[/'
    exit 4
fi

# parse arguments
ARGS=()
ARGS+=("nogui")
ARGS+=("import")
while [[ $# -gt 0 ]]
do
case $1 in
    -h|--help)
    java -jar -Dmf.cfg=$MFLUX_CFG $MFLUX_ATERM nogui help import | sed 's/import:/aterm-import:/' | sed 's/import \[/aterm-import \[/'
    exit 0
    ;;
    *)    
    ARGS+=("$1")
    shift
    ;;
esac
done

# restore arguments
set -- "${ARGS[@]}"

# execute import command via aterm
java -jar -Dmf.cfg=$MFLUX_CFG $MFLUX_ATERM ${1+"$@"}
