#!/bin/bash

# aterm.jar location
export MFLUX_ATERM=/opt/mediaflux/bin/aterm.jar

# mflux.cfg location
export MFLUX_CFG=$HOME/.Arcitecta/mflux.cfg

# aterm.jar download link. In case of $MFLUX_ATERM does not exist. This script tries downloading aterm.jar from the link below to the same directory:
ATERM_DOWNLOAD_LINK=https://mediaflux.vicnode.org.au/mflux/aterm.jar

# check if java exists
if [[ -z $(which java) ]]; then
    echo "Error: cannot find java." 1>&2
    exit 1
fi


SCRIPT_DIR=$(dirname $0)

# check if aterm.jar exists
if [[ -z $MFLUX_ATERM || ! -f $MFLUX_ATERM ]]; then
    if [[ -f ${SCRIPT_DIR}/aterm.jar ]]; then
        MFLUX_ATERM=${SCRIPT_DIR}/aterm.jar
    else
        if [[ ! -z $(which curl) ]]; then
            curl -o ${SCRIPT_DIR}/aterm.jar ${ATERM_DOWNLOAD_LINK} || exit 21
            MFLUX_ATERM=${SCRIPT_DIR}/aterm.jar
        else
            if [[ ! -z $(which wget) ]]; then
                wget -O ${SCRIPT_DIR}/aterm.jar ${ATERM_DOWNLOAD_LINK} || exit 22
                MFLUX_ATERM=${SCRIPT_DIR}/aterm.jar
            else
               echo "Error: cannot find aterm.jar." 1>&2
               exit 2
            fi
        fi
    fi
fi

# check if mflux.cfg exists
if [[ -z $MFLUX_CFG || ! -f $MFLUX_CFG ]]; then
    if [[ -f $HOME/.Arcitecta/mflux.cfg ]]; then
        MFLUX_CFG=$HOME/.Arcitecta/mflux.cfg
    else
        if [[ -f ${SCRIPT_DIR}/mflux.cfg ]]; then
            MFLUX_CFG=${SCRIPT_DIR}/mflux.cfg
        else
            echo "Error: cannot find mflux.cfg." 1>&2
            exit 3
        fi
    fi
fi

# show usage if no arguments specified
if [[ $# -eq 0 ]]; then
    echo "Error: missing arguments." 1>&2
    java -jar -Dmf.cfg=$MFLUX_CFG $MFLUX_ATERM nogui help import | sed 's/import:/aterm-import:/' | sed 's/import \[/aterm-import \[/'
    exit 4
fi

# parse arguments
ARGS=()
ARGS+=("nogui")
ARGS+=("import")
while [[ $# -gt 0 ]]
do
case $1 in
    -h|--help)
    java -jar -Dmf.cfg=$MFLUX_CFG $MFLUX_ATERM nogui help import | sed 's/import:/aterm-import:/' | sed 's/import \[/aterm-import \[/'
    exit 0
    ;;
    *)    
    ARGS+=("$1")
    shift
    ;;
esac
done

# restore arguments
set -- "${ARGS[@]}"

# execute import command via aterm
java -jar -Dmf.cfg=$MFLUX_CFG $MFLUX_ATERM ${1+"$@"}
